### PR TITLE
Add `isSaving` state to project title and description

### PR DESCRIPTION
**Pull request by jeffdaley**
Adds an `isSaving` spinner to the project title and description fields.

### CODE REVIEW

**Review by jfreda — COMMENTED** [review]
If I'm understanding this correctly, I'm not sure it would work if someone were to very quickly save a title and then a description because this is tracking each saving state separately and we're not doing any enqueueing of the async tasks (and the save function as-is wouldn't be able to differentiate between saving each field). It seems like the easiest thing would be to just make one saving state (like we do for the sidebar), or else make changes to support saving each field separately. Let me know if you think I'm misunderstanding the logic though.

**Comment by jeffdaley** [comment]
> If I'm understanding this correctly, I'm not sure it would work if someone were to very quickly save a title and then a description because this is tracking each saving state separately and we're not doing any enqueueing of the async tasks (and the save function as-is wouldn't be able to differentiate between saving each field). It seems like the easiest thing would be to just make one saving state (like we do for the sidebar), or else make changes to support saving each field separately. Let me know if you think I'm misunderstanding the logic though.

I changed the `save` task to be `restartable` to handle the edge case where a save attempt is made while another is in progress. In this case, you'd see two spinners. For general usage (editing one at a time, respecting the short `isSaving` state), a single spinner looks better.

**Comment by jfreda** [comment]
> I changed the `save` task to be `restartable` to handle the edge case where a save attempt is made while another is in progress. In this case, you'd see two spinners. For general usage (editing one at a time, respecting the short `isSaving` state), a single spinner looks better.

Okay, yeah agree about the UX, but I was just thinking about the functionality. I'm wondering if there still might be an edge case where the first task fails and the request gets lost, but I'm okay with leaving that for later if it's a possibility.

**Review by jfreda — APPROVED** [review]

**Comment by jeffdaley** [comment]
Ah, looking back at it, I was under the assumption that we always saved title, description and status regardless of which attribute was changing. That isn't the case so I'm switching to an `enqueue` task. Sorry for confusing things.

**Pull request merged**
